apiVersion: apps/v1
kind: Deployment
metadata:
  name: requester-deployment
  namespace: ksox-finance
  labels:
    app: requester
spec:
  selector:
    matchLabels:
      app: requester
  template:
    metadata:
      labels:
        app: requester
    spec:
      containers:
        - name: requester
          image: requester
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 1000Mi
              cpu: 1000m
            limits:
              memory: 2000Mi
              cpu: 2000m
