apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: neonevm-requester
build:
  artifacts:
    - image: requester
      context: ./
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - ./k8s/resources
